version: '3.3'
services:
  leimingshop-elasticsearch:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-elasticsearch:1.0
    container_name: leimingshop-elasticsearch
    environment:
      - node.name=master
      - cluster.name=leimingshop
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es01/data:/usr/share/elasticsearch/data
      - ./es01/logs:/usr/share/elasticsearch/logs
    restart: on-failure:10
    ports:
      - 9200:9200
    networks:
      - leimingshop
  leimingshop-mysql:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-mysql:1.0
    container_name: leimingshop-mysql
    restart: on-failure:10
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    networks:
      - leimingshop
    volumes:
      - ./mysql/data:/var/lib/mysql
  leimingshop-redis:
    image: redis
    container_name: leimingshop-redis
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure:10
    command: redis-server /etc/redis/redis.conf --port 6379 --requirepass 123456  --appendonly yes
    ports:
      - 6379:6379
    networks:
      - leimingshop
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
  leimingshop-tracker:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-fastdfs-tracker:1.0
    container_name: leimingshop-fastdfs-tracker
    restart: on-failure:10
    ports:
      - 22122:22122
    networks:
      - leimingshop
    volumes:
      - ./fdfs/tracker:/var/fdfs
  leimingshop-storage:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-fastdfs-storage:1.0
    container_name: leimingshop-fastdfs-storage
    restart: on-failure:10
    ports:
      - 8888:8888
    environment:
      - TRACKER_SERVER=tracker:22122
      - GROUP_NAME=group1
    networks:
      - leimingshop
    volumes:
      - ./fdfs/storage:/var/fdfs
    links:
      - leimingshop-tracker:tracker
  leimingshop-rabbtitmq:
    image: rabbitmq:3.7.7-management
    container_name: leimingshop-rabbitmq
    restart: on-failure:10
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=leimingshop
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - leimingshop
  leimingshop-mongodb:
    image: mongo
    container_name: leimingshop-mongodb
    restart: on-failure:10
    ports:
      - 27017:27017
    networks:
      - leimingshop
    volumes:
      - ./mongodb:/data/db
  leimingshop-admin-api:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-admin-api:1.0
    container_name: leimingshop-admin-api
    volumes:
      - ./leimingshop/logs:/app/logs
    restart: on-failure:10
    ports:
      - 28081:28081
    networks:
      - leimingshop
    links:
      - leimingshop-mysql:leimingshop-mysql
      - leimingshop-tracker:leimingshop-fastdfs
      - leimingshop-mongodb:leimingshop-mongodb
      - leimingshop-rabbtitmq:leimingshop-rabbitmq
      - leimingshop-elasticsearch:leimingshop-elasticsearch
      - leimingshop-redis:leimingshop-redis
  leimingshop-seller-api:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-seller-api:1.0
    container_name: leimingshop-seller-api
    volumes:
      - ./leimingshop/logs:/app/logs
    restart: on-failure:10
    ports:
      - 28080:28080
    networks:
      - leimingshop
    links:
      - leimingshop-mysql:leimingshop-mysql
      - leimingshop-tracker:leimingshop-fastdfs
      - leimingshop-mongodb:leimingshop-mongodb
      - leimingshop-rabbtitmq:leimingshop-rabbitmq
      - leimingshop-elasticsearch:leimingshop-elasticsearch
      - leimingshop-redis:leimingshop-redis
  leimingshop-web-api:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-web-api:1.0
    container_name: leimingshop-web-api
    volumes:
      - ./leimingshop/logs:/app/logs
    restart: on-failure:10
    ports:
      - 17070:17070
    networks:
      - leimingshop
    links:
      - leimingshop-mysql:leimingshop-mysql
      - leimingshop-tracker:leimingshop-fastdfs
      - leimingshop-mongodb:leimingshop-mongodb
      - leimingshop-rabbtitmq:leimingshop-rabbitmq
      - leimingshop-elasticsearch:leimingshop-elasticsearch
      - leimingshop-redis:leimingshop-redis
  leimingshop-mq-consumer:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-mq-consumer:1.0
    container_name: leimingshop-mq-consumer
    volumes:
      - ./leimingshop/logs:/app/logs
    restart: on-failure:10
    ports:
      - 48080:48080
    networks:
      - leimingshop
    links:
      - leimingshop-mysql:leimingshop-mysql
      - leimingshop-tracker:leimingshop-fastdfs
      - leimingshop-mongodb:leimingshop-mongodb
      - leimingshop-rabbtitmq:leimingshop-rabbitmq
      - leimingshop-elasticsearch:leimingshop-elasticsearch
      - leimingshop-redis:leimingshop-redis
  leimingshop-frontend:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-frontend:1.0
    container_name: leimingshop-frontend
    restart: on-failure:10
    ports:
      - 80:80
    networks:
      - leimingshop
    links:
      - leimingshop-web-api:web.api.com
      - leimingshop-seller-api:seller.api.com
      - leimingshop-admin-api:admin.api.com
      - leimingshop-pc:pc.node.com
      - leimingshop-storage:image.nginx.com
  leimingshop-pc:
    image: harbor.shop7.leimingtech.com/leimingshop/leimingshop-pc:1.0
    container_name: leimingshop-pc
    restart: on-failure:10
    ports:
      - 8000:8000
    networks:
      - leimingshop
networks:
  leimingshop:
    external: false
